import type { Metadata } from "next";
import { Geist, Geist_Mono ,Exo} from "next/font/google";
import "./globals.css";
import Navbar from "./_components/Navbar";
import Footer from "./_components/Footer";
import ToastProvider from "@/toast.provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});



export const metadata: Metadata = {
  title: "FreshCart",
  description: "Generated by create next app",
};

const exo = Exo({
  variable: "--font-Exo",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "900"],

});







export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable}  ${exo.variable}    font-Exo   antialiased`}
    >
   <body className={`${exo.className} min-h-full`}>
      
      <Navbar/>
       
        <ToastProvider>
        {children}
        
  
    
    </ToastProvider>
        <Footer/>
        
     
        </body>

        
    </html>
  );
}
